# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dartDistanceMatrixCpp <- function(snpData, sampleWiseAnalysis = FALSE, nThreads = 1L) {
    .Call('_dartVarietalID_dartDistanceMatrixCpp', PACKAGE = 'dartVarietalID', snpData, sampleWiseAnalysis, nThreads)
}

